baseURL = "https://www.polycode.in/"
relativeURLs = "True"
languageCode = "en-us"
title = "Polycode Services"
theme = 'digitalgarden'

googleAnalytics = "UA-PROPERTY_ID"

[Params]
  description = "Polycode Services in a nutshell"
  images = ['/images/logo-polycode.png']
  custom_css = ["css/tailwind.css", "css/main.css"]
  favicon = '/images/logo-polycode.png'

[Params.newsletter]
  title = "Polycode Newsletter"
  description = "Weekly insights into digital space"
  path = "https://www.getrevue.co/profile/polycode/add_subscriber"

[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1
[[menu.main]]
  name = 'Articles'
  url = '/articles'
  weight = 3
[[menu.main]]
  name = 'About us'
  url = '/about-us'
  weight = 5

[[menu.social]]
  name = 'Email'
  url = 'mailto:asish.panda@polycode.in'
  weight = 1



# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true

  
enableInlineShortcodes = true

    
